### ISSUE TITLE
error on windows 10

### ISSUE THREAD

**Issue by trzmaxim** [jagrem/babel-resolve-relative-module#2]
In some cases, the path is wrong.

Result of tests:

```
  Resolve module module
    √ returns a function
    √ complains if the path I pass in is not a string
    resolving relative paths
      1) resolves a relative path in a sybling directory
      2) resolves a relative path in a parent directory
      3) resolves a relative path in a child directory
      √ does not resolve an unknown relative path
      - resolves a relative path in the root directory


  3 passing (17ms)
  1 pending
  3 failing

  1) Resolve module module resolving relative paths resolves a relative path in a sybling directory:

      AssertionError: expected '.\\..\\1\\index' to equal './../1/index'
      + expected - actual

      -.\..\1\index
      +./../1/index

      at Context.<anonymous> (index.js:24:13)
      at callFn (e:\w\babel-resolve-relative-module\node_modules\mocha\lib\runnable.js:286:21)
      at Test.Runnable.run (e:\w\babel-resolve-relative-module\node_modules\mocha\lib\runnable.js:279:7)
      at Runner.runTest (e:\w\babel-resolve-relative-module\node_modules\mocha\lib\runner.js:421:10)
      at e:\w\babel-resolve-relative-module\node_modules\mocha\lib\runner.js:528:12
      at next (e:\w\babel-resolve-relative-module\node_modules\mocha\lib\runner.js:341:14)
      at e:\w\babel-resolve-relative-module\node_modules\mocha\lib\runner.js:351:7
      at next (e:\w\babel-resolve-relative-module\node_modules\mocha\lib\runner.js:283:14)
      at e:\w\babel-resolve-relative-module\node_modules\mocha\lib\runner.js:314:7
      at done (e:\w\babel-resolve-relative-module\node_modules\mocha\lib\runnable.js:247:5)

  2) Resolve module module resolving relative paths resolves a relative path in a parent directory:

      AssertionError: expected '.\\..\\index' to equal './../index'
      + expected - actual

      -.\..\index
      +./../index

      at Context.<anonymous> (index.js:29:13)
      at callFn (e:\w\babel-resolve-relative-module\node_modules\mocha\lib\runnable.js:286:21)
      at Test.Runnable.run (e:\w\babel-resolve-relative-module\node_modules\mocha\lib\runnable.js:279:7)
      at Runner.runTest (e:\w\babel-resolve-relative-module\node_modules\mocha\lib\runner.js:421:10)
      at e:\w\babel-resolve-relative-module\node_modules\mocha\lib\runner.js:528:12
      at next (e:\w\babel-resolve-relative-module\node_modules\mocha\lib\runner.js:341:14)
      at e:\w\babel-resolve-relative-module\node_modules\mocha\lib\runner.js:351:7
      at next (e:\w\babel-resolve-relative-module\node_modules\mocha\lib\runner.js:283:14)
      at e:\w\babel-resolve-relative-module\node_modules\mocha\lib\runner.js:314:7
      at done (e:\w\babel-resolve-relative-module\node_modules\mocha\lib\runnable.js:247:5)

  3) Resolve module module resolving relative paths resolves a relative path in a child directory:

      AssertionError: expected '.\\3\\index' to equal './3/index'
      + expected - actual

      -.\3\index
      +./3/index

      at Context.<anonymous> (index.js:34:13)
      at callFn (e:\w\babel-resolve-relative-module\node_modules\mocha\lib\runnable.js:286:21)
      at Test.Runnable.run (e:\w\babel-resolve-relative-module\node_modules\mocha\lib\runnable.js:279:7)
      at Runner.runTest (e:\w\babel-resolve-relative-module\node_modules\mocha\lib\runner.js:421:10)
      at e:\w\babel-resolve-relative-module\node_modules\mocha\lib\runner.js:528:12
      at next (e:\w\babel-resolve-relative-module\node_modules\mocha\lib\runner.js:341:14)
      at e:\w\babel-resolve-relative-module\node_modules\mocha\lib\runner.js:351:7
      at next (e:\w\babel-resolve-relative-module\node_modules\mocha\lib\runner.js:283:14)
      at e:\w\babel-resolve-relative-module\node_modules\mocha\lib\runner.js:314:7
      at done (e:\w\babel-resolve-relative-module\node_modules\mocha\lib\runnable.js:247:5)




events.js:141
      throw er; // Unhandled 'error' event
      ^
 Error: 3 tests failed.
npm ERR! Test failed.  See above for more details.
```

**Comment by jagrem** [comment]
I'll have a look at this when I have access to a Windows 10 machine again.
Looks like I've neglected Windows compatibility when using Node's `path`.

**Comment by jagrem** [comment]
Looks like test path expectations were not correct, fixed in a04ef1e6ff6aa53fa68e9b63eab1d8ab23c9e093

I don't see any evidence however that any of the paths are incorrect on Windows.

**Comment by trzmaxim** [comment]
`.\\..\\1\\index` incorrect path for module node.js
Your plugin should always calculate the path with `/`.

**Comment by jagrem** [comment]
OK, I'll investigate.

**Comment by ntucker** [comment]
Confirmed this is an issue for me.

**Comment by pentateu** [comment]
Hi any update for the fix for windows ?

I'm planning to use your plugin.. just want to confirm it is compatible with Windows.
